// <auto-generated />
using System;
using LazyMoon.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LazyMoon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221108015322_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LazyMoon.Model.TTS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<bool>("TTSEnable")
                        .HasColumnType("boolean");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TTS");
                });

            modelBuilder.Entity("LazyMoon.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("LoginId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TTSId")
                        .HasColumnType("integer");

                    b.Property<int>("ValorantRankId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TTSId");

                    b.HasIndex("ValorantRankId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LazyMoon.Model.ValorantRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("currentRank")
                        .HasColumnType("integer");

                    b.Property<int>("currentScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ValorantRanks");
                });

            modelBuilder.Entity("LazyMoon.Model.Voice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Pitch")
                        .HasColumnType("double precision");

                    b.Property<int?>("TTSId")
                        .HasColumnType("integer");

                    b.Property<bool>("Use")
                        .HasColumnType("boolean");

                    b.Property<int>("VoiceMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TTSId");

                    b.ToTable("Voices");
                });

            modelBuilder.Entity("LazyMoon.Model.User", b =>
                {
                    b.HasOne("LazyMoon.Model.TTS", "TTS")
                        .WithMany()
                        .HasForeignKey("TTSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LazyMoon.Model.ValorantRank", "ValorantRank")
                        .WithMany()
                        .HasForeignKey("ValorantRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TTS");

                    b.Navigation("ValorantRank");
                });

            modelBuilder.Entity("LazyMoon.Model.Voice", b =>
                {
                    b.HasOne("LazyMoon.Model.TTS", null)
                        .WithMany("Voices")
                        .HasForeignKey("TTSId");
                });

            modelBuilder.Entity("LazyMoon.Model.TTS", b =>
                {
                    b.Navigation("Voices");
                });
#pragma warning restore 612, 618
        }
    }
}
